#include "nppthemes/ThemeXmlCompiler.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <string>

#include <pugixml.hpp>

#ifdef _WIN32
#include <windows.h>
#endif

namespace nppthemes {
namespace {

constexpr std::uintmax_t maxThemeBytes = 16U * 1024U * 1024U;

[[nodiscard]] std::string lower(std::string value) {
    std::transform(value.begin(), value.end(), value.begin(),
                   [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return value;
}

[[nodiscard]] Color colorFromStyleName(const ThemeProfile& profile, const std::string& styleName) {
    const auto name = lower(styleName);
    if (name.find("comment") != std::string::npos || name.find("remark") != std::string::npos) {
        return profile.palette.comment;
    }
    if (name.find("string") != std::string::npos || name.find("character") != std::string::npos ||
        name.find("quoted") != std::string::npos || name.find("heredoc") != std::string::npos) {
        return profile.palette.string;
    }
    if (name.find("number") != std::string::npos || name.find("numeric") != std::string::npos ||
        name.find("float") != std::string::npos) {
        return profile.palette.number;
    }
    if (name.find("keyword") != std::string::npos || name.find("instruction") != std::string::npos ||
        name.find("reserved") != std::string::npos || name.find("preprocessor") != std::string::npos) {
        return profile.palette.keyword;
    }
    if (name.find("function") != std::string::npos || name.find("method") != std::string::npos ||
        name.find("command") != std::string::npos) {
        return profile.palette.function;
    }
    if (name.find("class") != std::string::npos || name.find("type") != std::string::npos ||
        name.find("interface") != std::string::npos || name.find("structure") != std::string::npos) {
        return profile.palette.type;
    }
    if (name.find("operator") != std::string::npos || name.find("delimiter") != std::string::npos ||
        name.find("symbol") != std::string::npos || name.find("tag") != std::string::npos) {
        return profile.palette.op;
    }
    if (name.find("url") != std::string::npos || name.find("link") != std::string::npos ||
        name.find("active") != std::string::npos) {
        return profile.palette.accent;
    }
    if (name.find("line number") != std::string::npos || name.find("whitespace") != std::string::npos ||
        name.find("indent guide") != std::string::npos || name.find("inactive") != std::string::npos) {
        return profile.palette.muted;
    }
    return profile.palette.foreground;
}

void setColorAttribute(pugi::xml_node node, const char* attributeName, Color color) {
    auto attribute = node.attribute(attributeName);
    if (!attribute) {
        attribute = node.append_attribute(attributeName);
    }
    const auto formatted = formatHexColor(color).substr(1);
    attribute.set_value(formatted.c_str());
}

void setStringAttribute(pugi::xml_node node, const char* attributeName, const std::string& value) {
    auto attribute = node.attribute(attributeName);
    if (!attribute) {
        attribute = node.append_attribute(attributeName);
    }
    attribute.set_value(value.c_str());
}

} // namespace

ThemeCompileResult compileThemeXml(const std::filesystem::path& source, const std::filesystem::path& destination,
                                   const ThemeProfile& profile) {
    ThemeCompileResult result;
    const auto validation = validateProfile(profile);
    if (!validation.empty()) {
        result.error = validation.front();
        return result;
    }

    std::error_code error;
    const auto sourceSize = std::filesystem::file_size(source, error);
    if (error || sourceSize > maxThemeBytes) {
        result.error = error ? "Unable to inspect source theme" : "Source theme exceeds 16 MiB limit";
        return result;
    }
    if (std::filesystem::equivalent(source, destination, error) && !error) {
        result.error = "Source and destination theme paths must differ";
        return result;
    }

    pugi::xml_document document;
    const auto loaded = document.load_file(source.c_str(), pugi::parse_default, pugi::encoding_utf8);
    if (!loaded) {
        result.error = std::string("Unable to parse source theme: ") + loaded.description();
        return result;
    }
    const auto root = document.child("NotepadPlus");
    if (!root || !root.child("LexerStyles") || !root.child("GlobalStyles")) {
        result.error = "Source theme is missing required NotepadPlus style sections";
        return result;
    }
    const std::string generator =
        "Generated by NppThemes; profile=" + profile.id + "; schema=" + std::to_string(profile.schemaVersion);
    document.prepend_child(pugi::node_comment).set_value(generator.c_str());

    for (auto style : document.select_nodes("/NotepadPlus/GlobalStyles/WidgetStyle")) {
        auto node = style.node();
        const std::string name = node.attribute("name").as_string();
        setColorAttribute(node, "fgColor", colorFromStyleName(profile, name));
        setColorAttribute(node, "bgColor", profile.palette.background);
        if (lower(name) == "default style") {
            setStringAttribute(node, "fontName", profile.fontFamily);
            setStringAttribute(node, "fontSize", std::to_string(profile.fontSizePt));
        }
        ++result.stylesUpdated;
    }

    for (auto lexer : document.select_nodes("/NotepadPlus/LexerStyles/LexerType")) {
        const std::string language = lexer.node().attribute("name").as_string();
        for (auto style = lexer.node().child("WordsStyle"); style; style = style.next_sibling("WordsStyle")) {
            const std::string name = style.attribute("name").as_string();
            const int styleId = style.attribute("styleID").as_int();
            Color foreground = colorFromStyleName(profile, name);
            if (foreground == profile.palette.foreground) {
                foreground = semanticColorForStyle(profile, language, styleId, foreground);
            }
            setColorAttribute(style, "fgColor", foreground);
            setColorAttribute(style, "bgColor", profile.palette.background);
            ++result.stylesUpdated;
        }
    }

    error.clear();
    std::filesystem::create_directories(destination.parent_path(), error);
    if (error) {
        result.error = "Unable to create destination directory: " + error.message();
        return result;
    }

    auto temporary = destination;
    temporary += L".tmp";
    if (!document.save_file(temporary.c_str(), "    ", pugi::format_default, pugi::encoding_utf8)) {
        result.error = "Unable to write temporary theme file";
        return result;
    }
    pugi::xml_document verification;
    const auto verified = verification.load_file(temporary.c_str(), pugi::parse_default, pugi::encoding_utf8);
    if (!verified || !verification.child("NotepadPlus")) {
        result.error = "Generated theme failed post-write validation";
        std::filesystem::remove(temporary, error);
        return result;
    }

#ifdef _WIN32
    if (!::MoveFileExW(temporary.c_str(), destination.c_str(), MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH)) {
        result.error = "Unable to atomically install generated theme";
        std::filesystem::remove(temporary, error);
        return result;
    }
#else
    std::filesystem::rename(temporary, destination, error);
    if (error) {
        result.error = "Unable to atomically install generated theme: " + error.message();
        std::filesystem::remove(temporary, error);
        return result;
    }
#endif

    result.success = true;
    return result;
}

} // namespace nppthemes
